INSERT INTO "companies" ("id", "name", "trade_name", "document", "email", "phone", "status", "settings", "created_at", "updated_at", "plan", "subscription_status") VALUES (1, 'Anjos', 'Anjos', NULL, 'contato@anjos.com.br', NULL, 'active', '{"timezone":"America/Fortaleza","currency":"BRL"}', '2026-10-07 18:02:03', NULL, 'standard', 'active');
INSERT INTO "stores" ("id", "company_id", "name", "code", "city", "state", "status", "created_at", "updated_at") VALUES (1, 1, 'Anjos Balsas', 'BALSAS', 'Balsas', 'MA', 'active', '2026-10-07 18:02:03', NULL);
INSERT INTO "stores" ("id", "company_id", "name", "code", "city", "state", "status", "created_at", "updated_at") VALUES (2, 1, 'Anjos Imperatriz', 'IMPERATRIZ', 'Imperatriz', 'MA', 'active', '2026-10-07 18:02:03', NULL);
INSERT INTO "roles" ("id", "company_id", "slug", "name", "description", "is_system", "created_at") VALUES (1, NULL, 'master', 'Master', 'Controle global da plataforma — Oficial Link Sistemas', 1, '2026-10-07 18:02:03');
INSERT INTO "roles" ("id", "company_id", "slug", "name", "description", "is_system", "created_at") VALUES (2, NULL, 'company_admin', 'Administrador', 'Acesso completo dentro da própria empresa', 1, '2026-10-07 18:02:03');
INSERT INTO "roles" ("id", "company_id", "slug", "name", "description", "is_system", "created_at") VALUES (3, NULL, 'supervisor', 'Supervisor', 'Acompanhamento de equipe e lojas, sem alterações críticas', 1, '2026-10-07 18:02:03');
INSERT INTO "roles" ("id", "company_id", "slug", "name", "description", "is_system", "created_at") VALUES (4, NULL, 'seller', 'Vendedor', 'Acesso operacional básico', 1, '2026-10-07 18:02:03');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.overview.view', 'Plataforma', 'Visão geral da plataforma');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.stores.view', 'Plataforma', 'Visualizar lojas de qualquer empresa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.stores.manage', 'Plataforma', 'Gerenciar lojas de qualquer empresa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.users.view', 'Plataforma', 'Visualizar usuários de qualquer empresa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.users.manage', 'Plataforma', 'Gerenciar usuários de qualquer empresa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.audit.view', 'Plataforma', 'Visualizar auditoria da plataforma');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.settings.view', 'Plataforma', 'Visualizar configurações da plataforma');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.settings.manage', 'Plataforma', 'Alterar configurações da plataforma');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('sales.view', 'Vendas', 'Visualizar vendas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('sales.create', 'Vendas', 'Registrar venda');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('sales.edit', 'Vendas', 'Editar venda');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('sales.cancel', 'Vendas', 'Cancelar venda');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('targets.view', 'Metas', 'Visualizar metas e desempenho');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('targets.create', 'Metas', 'Cadastrar meta');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('targets.edit', 'Metas', 'Editar meta');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('targets.delete', 'Metas', 'Excluir meta');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('ranking.view', 'Ranking', 'Visualizar ranking de vendedores e lojas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('customers.view', 'Clientes', 'Visualizar clientes');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('customers.create', 'Clientes', 'Cadastrar cliente');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('customers.edit', 'Clientes', 'Editar cliente');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('customers.delete', 'Clientes', 'Excluir cliente');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('products.view', 'Produtos', 'Visualizar produtos');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('products.create', 'Produtos', 'Cadastrar produto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('products.edit', 'Produtos', 'Editar produto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('products.delete', 'Produtos', 'Excluir produto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('stock.view', 'Estoque', 'Visualizar saldos e movimentações');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('stock.move', 'Estoque', 'Registrar entrada e saída manual');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('stock.adjust', 'Estoque', 'Ajustar saldo (inventário)');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('suppliers.view', 'Fornecedores', 'Visualizar fornecedores');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('suppliers.create', 'Fornecedores', 'Cadastrar fornecedor');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('suppliers.edit', 'Fornecedores', 'Editar fornecedor');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('suppliers.delete', 'Fornecedores', 'Excluir fornecedor');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('purchases.view', 'Compras', 'Visualizar compras');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('purchases.create', 'Compras', 'Cadastrar compra (rascunho)');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('purchases.edit', 'Compras', 'Editar compra em rascunho');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('purchases.receive', 'Compras', 'Receber compra (entrada no estoque)');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('purchases.cancel', 'Compras', 'Cancelar compra');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('reports.view', 'Relatórios', 'Visualizar relatórios operacionais');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('payables.view', 'Contas a pagar', 'Visualizar contas a pagar');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('payables.create', 'Contas a pagar', 'Lançar título a pagar');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('payables.update', 'Contas a pagar', 'Editar título em aberto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('payables.pay', 'Contas a pagar', 'Pagar título');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('payables.cancel', 'Contas a pagar', 'Cancelar título em aberto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('payables.delete', 'Contas a pagar', 'Excluir título manual em aberto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('receivables.view', 'Contas a receber', 'Visualizar contas a receber');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('receivables.create', 'Contas a receber', 'Lançar título a receber');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('receivables.update', 'Contas a receber', 'Editar título em aberto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('receivables.receive', 'Contas a receber', 'Receber título');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('receivables.cancel', 'Contas a receber', 'Cancelar título em aberto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('receivables.delete', 'Contas a receber', 'Excluir título manual em aberto');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.billing.view', 'Plataforma', 'Visualizar cobranças SaaS das empresas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.billing.manage', 'Plataforma', 'Gerenciar cobranças SaaS das empresas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('tasks.view', 'Tarefas', 'Visualizar tarefas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('tasks.create', 'Tarefas', 'Criar tarefa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('tasks.edit', 'Tarefas', 'Editar tarefa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('tasks.delete', 'Tarefas', 'Excluir tarefa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('tasks.complete', 'Tarefas', 'Concluir/reabrir tarefa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('agenda.view', 'Agenda', 'Visualizar agenda');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('agenda.create', 'Agenda', 'Criar compromisso');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('agenda.edit', 'Agenda', 'Editar compromisso');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('agenda.delete', 'Agenda', 'Cancelar/excluir compromisso');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('checklists.view', 'Checklists', 'Visualizar checklists');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('checklists.create', 'Checklists', 'Criar checklist');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('checklists.edit', 'Checklists', 'Editar checklist');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('checklists.delete', 'Checklists', 'Excluir/cancelar checklist');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('checklists.complete', 'Checklists', 'Executar/concluir itens e checklist');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('notifications.view', 'Notificações', 'Visualizar notificações');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('notifications.manage', 'Notificações', 'Gerenciar notificações da empresa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.companies.view', 'Plataforma', 'Visualizar empresas cadastradas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('platform.companies.manage', 'Plataforma', 'Cadastrar, editar e suspender empresas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('dashboard.view', 'Dashboard', 'Visualizar o painel inicial');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('stores.view', 'Lojas', 'Visualizar lojas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('stores.manage', 'Lojas', 'Cadastrar e editar lojas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('users.view', 'Usuários', 'Visualizar usuários');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('users.manage', 'Usuários', 'Cadastrar, editar e redefinir senhas');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('company.settings.view', 'Empresa', 'Visualizar dados da empresa');
INSERT INTO "permissions" ("code", "module", "description") VALUES ('company.settings.manage', 'Empresa', 'Editar dados e configurações da empresa');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.overview.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.companies.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.companies.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.stores.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.stores.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.users.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.users.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.audit.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.settings.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'platform.settings.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'dashboard.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'stores.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'stores.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'users.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'users.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'company.settings.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'company.settings.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'sales.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'sales.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'sales.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'sales.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'targets.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'targets.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'targets.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'targets.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'ranking.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'customers.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'customers.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'customers.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'customers.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'products.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'products.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'products.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'products.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'stock.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'stock.move');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'stock.adjust');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'suppliers.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'suppliers.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'suppliers.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'suppliers.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'purchases.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'purchases.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'purchases.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'purchases.receive');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'purchases.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'reports.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'payables.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'payables.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'payables.update');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'payables.pay');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'payables.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'payables.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'receivables.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'receivables.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'receivables.update');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'receivables.receive');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'receivables.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'receivables.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'tasks.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'tasks.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'tasks.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'tasks.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'tasks.complete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'agenda.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'agenda.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'agenda.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'agenda.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'checklists.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'checklists.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'checklists.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'checklists.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'checklists.complete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (1, 'notifications.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'dashboard.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'stores.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'stores.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'users.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'users.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'company.settings.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'company.settings.manage');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'sales.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'sales.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'sales.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'sales.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'targets.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'targets.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'targets.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'targets.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'ranking.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'customers.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'customers.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'customers.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'customers.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'products.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'products.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'products.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'products.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'stock.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'stock.move');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'stock.adjust');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'suppliers.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'suppliers.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'suppliers.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'suppliers.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'purchases.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'purchases.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'purchases.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'purchases.receive');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'purchases.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'reports.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'payables.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'payables.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'payables.update');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'payables.pay');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'payables.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'payables.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'receivables.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'receivables.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'receivables.update');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'receivables.receive');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'receivables.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'receivables.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'tasks.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'tasks.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'tasks.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'tasks.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'tasks.complete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'agenda.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'agenda.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'agenda.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'agenda.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'checklists.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'checklists.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'checklists.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'checklists.delete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'checklists.complete');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (2, 'notifications.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'dashboard.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'stores.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'users.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'company.settings.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'sales.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'sales.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'sales.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'targets.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'targets.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'targets.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'ranking.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'customers.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'customers.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'customers.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'products.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'products.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'products.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'stock.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'stock.move');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'stock.adjust');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'suppliers.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'suppliers.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'suppliers.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'purchases.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'purchases.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'purchases.edit');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'purchases.receive');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'reports.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'payables.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'payables.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'payables.update');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'payables.pay');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'payables.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'receivables.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'receivables.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'receivables.update');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'receivables.receive');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (3, 'receivables.cancel');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'dashboard.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'sales.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'sales.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'targets.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'ranking.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'customers.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'customers.create');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'products.view');
INSERT INTO "role_permissions" ("role_id", "permission_code") VALUES (4, 'stock.view');
INSERT INTO "users" ("id", "company_id", "store_id", "role_id", "name", "email", "password_hash", "status", "last_login_at", "created_at", "updated_at", "must_change_password") VALUES (1, NULL, NULL, 1, 'Master Oficial Link', 'master@oficiallink.com.br', 'scrypt$16384$0395894b07e3f2faa4e0d7f23f061d46$0f6f655e7268fc58a11dcba28a1a50ca342ff74a642dba345c24729f046a599cd07b9bfd7aabfcf6a2886bfa5ad80feadd2ebc653a44967e96e884ad865fec67', 'active', NULL, '2026-10-07 18:02:03', NULL, 1);
INSERT INTO "users" ("id", "company_id", "store_id", "role_id", "name", "email", "password_hash", "status", "last_login_at", "created_at", "updated_at", "must_change_password") VALUES (2, 1, NULL, 2, 'Administrador Anjos', 'admin@anjos.com.br', 'scrypt$16384$ee64d6a541b5b7047da5d78a91239fc8$bc112a70d0db671ce413084d95549431a5f7919c44a961a3065d1c303f58bbe739c8a5127e1d23ef98ce61b41e74a03b3c27f79e3bb9ab7829f88c288211e689', 'active', NULL, '2026-10-07 18:02:03', NULL, 1);
INSERT INTO "users" ("id", "company_id", "store_id", "role_id", "name", "email", "password_hash", "status", "last_login_at", "created_at", "updated_at", "must_change_password") VALUES (3, 1, NULL, 3, 'Supervisor Anjos', 'supervisor@anjos.com.br', 'scrypt$16384$92b3b233ffe01a9da89f09a04fe51847$2ce04c765add648760a7a93b6dce3586277511f9be5c94cae92c8bfe285f45438172ed451ab8047b0b1417284f319d63bed80ca279370b78010560182c57e9e9', 'active', NULL, '2026-10-07 18:02:03', NULL, 1);
INSERT INTO "users" ("id", "company_id", "store_id", "role_id", "name", "email", "password_hash", "status", "last_login_at", "created_at", "updated_at", "must_change_password") VALUES (4, 1, 1, 4, 'Vendedor Anjos', 'vendedor@anjos.com.br', 'scrypt$16384$22aaca3d0aa8f742cb37fd9a64f41f14$482f35c606047b441f55f810d3438e9176c88abafbcd125f06ed8e6ef0e5a9f22d8b8e1fe5c95482b38e1ff0f8c7de519a15b23e877d56daf4247336189b6560', 'active', NULL, '2026-10-07 18:02:03', NULL, 1);
INSERT INTO "platform_settings" ("key", "value", "updated_at") VALUES ('maintenance_mode', '0', '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('dashboard', 'Dashboard', 'Painel inicial do ERP', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('sales', 'Vendas', 'Registro e gestão de vendas', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('customers', 'Clientes', 'Cadastro de clientes (estrutura preparada)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('products', 'Produtos', 'Catálogo de produtos (preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('stock', 'Estoque', 'Controle de estoque (preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('ranking', 'Ranking', 'Ranking de vendedores (preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('commissions', 'Comissões', 'Cálculo de comissões (preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('requests', 'Solicitações', 'Solicitações internas (preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('tasks', 'Tarefas', 'Tarefas e pendências (preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('payables', 'Contas a pagar', '(preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('receivables', 'Contas a receber', '(preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('suppliers', 'Fornecedores', '(preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('documents', 'Documentos', '(preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('reports', 'Relatórios', '(preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('notifications', 'Notificações', '(preparado)', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('targets', 'Metas', 'Metas comerciais por vendedor ou loja', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('purchases', 'Compras', 'Entrada de mercadoria com fornecedor', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('agenda', 'Agenda', 'Compromissos, reuniões e visitas', 1, '2026-10-07 18:02:02');
INSERT INTO "modules" ("slug", "name", "description", "is_official", "created_at") VALUES ('checklists', 'Checklists', 'Checklists e rotinas operacionais', 1, '2026-10-07 18:02:02');
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'dashboard', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'sales', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'targets', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'ranking', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'customers', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'products', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'stock', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'suppliers', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'purchases', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'reports', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'payables', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'receivables', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'tasks', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'agenda', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'checklists', 'active', '{}', '2026-10-07 18:02:03', NULL);
INSERT INTO "company_modules" ("company_id", "module_slug", "status", "settings", "created_at", "updated_at") VALUES (1, 'notifications', 'active', '{}', '2026-10-07 18:02:03', NULL);