name = "oficial-link-erp"
main = "server/src/worker.js"
compatibility_date = "2026-10-07"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]

[assets]
directory = "./web"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "oficial-link-erp"
migrations_dir = "d1/migrations"
database_id = "1b352475-1671-4fe6-93be-137633af5b72"

[[kv_namespaces]]
binding = "RATE_LIMIT"
id = "be0baa4668df41f4ac38ba383a280c6f"
preview_id = "be0baa4668df41f4ac38ba383a280c6f"

[vars]
NODE_ENV = "production"
APP_ORIGIN = "PENDENTE-RODADA-2"
SECURE_COOKIES = "1"
SESSION_TTL_HOURS = "8"
TRUST_PROXY = "1"
